import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is auto-generated by Next itself (regenerated on every
    // `next dev`/`next build`) - its triple-slash reference is Next's own
    // convention, not something to fix.
    ignores: [".next/**", "node_modules/**", "data/**", "resume/**", "public/**", "next-env.d.ts"],
  },
  {
    rules: {
      // Several agents intentionally don't use their AgentContext param
      // (see AgentContext in cms-intelligence/agents/types.ts) - the `_`
      // prefix is this codebase's existing convention for that, already
      // used across 9 agent files before this config existed.
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
  },
];

export default eslintConfig;
